// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Globalization;
using global::Rowles.LeanCorpus.Document;
using global::Rowles.LeanCorpus.Document.Fields;
using global::Rowles.LeanCorpus.Index.Indexer;
using global::Rowles.LeanCorpus.Mapping;
using global::Rowles.LeanCorpus.Linq;
using global::Rowles.LeanCorpus.Search.Searcher;

namespace Rowles.LeanCorpus.Tests.AOTSmoke;

public static class SmokeModelIndex
{
    public static LeanDocumentMap<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel> Map { get; } = new SmokeModelDocumentMap();

    public static class Fields
    {
        public static readonly LeanField<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel, string> Id = new("id", FieldType.String, true, true, true);
        public static readonly LeanField<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel, string> Title = new("title", FieldType.Text, true, true, false);
        public static readonly LeanField<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel, int> Count = new("count", FieldType.Numeric, true, true, true);
    }

    public static LeanDocument ToDocument(global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel value)
    {
        ArgumentNullException.ThrowIfNull(value);
        var doc = new LeanDocument();
            doc.Add(new StringField(Fields.Id.Name, value.Id, true));
        if (value.Title is not null)
            doc.Add(new TextField(Fields.Title.Name, value.Title, true));
        doc.Add(new NumericField(Fields.Count.Name, (double)value.Count, true));
        return doc;
    }

    public static IndexSchema CreateSchema(bool strict = true)
    {
        var schema = new IndexSchema { StrictMode = strict };
        schema.Add(new FieldMapping("id", FieldType.String) { IsStored = true, IsIndexed = true, IsRequired = true });
        schema.Add(new FieldMapping("title", FieldType.Text) { IsStored = true, IsIndexed = true, IsRequired = false });
        schema.Add(new FieldMapping("count", FieldType.Numeric) { IsStored = true, IsIndexed = true, IsRequired = true });
        return schema;
    }

    public static global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel FromStoredDocument(StoredDocument document)
    {
        var __Id = document.GetFirst(Fields.Id.Name);
        if (__Id is null) throw new InvalidOperationException("Missing required stored field: id");
        var __Title = document.GetFirst(Fields.Title.Name);
        var __Count__raw = document.GetFirst(Fields.Count.Name);
        if (__Count__raw is null) throw new InvalidOperationException("Missing required stored field: count");
        return new global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel()
        {
            Id = __Id!,
            Title = __Title,
            Count = checked((int)((long)double.Parse(__Count__raw!, NumberStyles.Float, CultureInfo.InvariantCulture)))
        };
    }

    /// <summary>
    /// Maps C# property names to field descriptors for the LINQ expression visitor.
    /// The JIT compiles this switch expression to a jump table (zero allocation).
    /// </summary>
    internal static global::Rowles.LeanCorpus.Linq.IFieldDescriptor? GetFieldDescriptor(string propertyName)
        => propertyName switch
        {
            "Id" => Fields.Id,
            "Title" => Fields.Title,
            "Count" => Fields.Count,
            _ => null
        };

    /// <summary>
    /// Returns a LINQ <see cref="global::Rowles.LeanCorpus.Linq.LeanQueryable{T}"/>
    /// that queries the index via the supplied <paramref name="searcher"/>.
    /// Lambda predicates (e.g. <c>.Where(d =&gt; d.Id == value)</c>) are translated into
    /// LeanCorpus query objects and executed directly against the index.
    /// </summary>
    public static global::Rowles.LeanCorpus.Linq.LeanQueryable<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel> AsQueryable(
        global::Rowles.LeanCorpus.Search.Searcher.IndexSearcher searcher)
        => new(searcher, Map, GetFieldDescriptor);
}

file sealed class SmokeModelDocumentMap : LeanDocumentMap<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel>
{
    public override string DocumentName => "SmokeModel";
    public override bool StrictSchema => true;

    public override IReadOnlyList<LeanFieldBinding<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel>> Fields { get; } = new LeanFieldBinding<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel>[]
    {
        new LeanFieldBinding<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel>("id", FieldType.String, true, true, true),
        new LeanFieldBinding<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel>("title", FieldType.Text, true, true, false),
        new LeanFieldBinding<global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel>("count", FieldType.Numeric, true, true, true)
    };

    public override LeanDocument ToDocument(global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel value) => SmokeModelIndex.ToDocument(value);
    public override global::Rowles.LeanCorpus.Tests.AOTSmoke.SmokeModel FromStoredDocument(StoredDocument document) => SmokeModelIndex.FromStoredDocument(document);
    public override IndexSchema CreateSchema(bool strict) => SmokeModelIndex.CreateSchema(strict);
}
